### ISSUE TITLE
[Bug]: Audio quality of music in the playlist are randomly stream between 64 and 256, and does not resize to 256 when streaming it again in the playlist

### ISSUE THREAD

**Issue by Javen1126** [ciderapp/Sabiiro-BugTracker#206]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Install Cider 2 through Microsoft Store on 18 May 2023 Malaysia time(GMT+8)

### Operating System Version

Windows 10 version 22H2

### Describe the Bug

Audio quality of the music randomly streams at 64 or 256 when streaming music through the playlist. The streamed track does not resize to 256 when I try to play previous song(which is that streamed track) in the playlist.

![Screenshot_1](https://github.com/ciderapp/Sabiiro-BugTracker/assets/77139046/372bdd10-ce9c-41e0-b6aa-4e1646e7ad84)
![Screenshot_3](https://github.com/ciderapp/Sabiiro-BugTracker/assets/77139046/d4b6d59c-154b-4fed-8d6b-7de7e0351636)

### Steps to Reproduce

1. Clicked on one of the track in song page/ Clicked on shuffle to stream music within a playlist
2. Noticed 64 on one of the track(track1)
3. Clicked on next to play next track(track2), track2 shows 256
4. Clicked on previous to stream track1, track1 still shows 64
5. Clicked on next to stream track2, track2 shows 256

### Anything else?

I noticed it only happens within playlist. When i play the tracks individually back and forth, they can stream 256, or able to resize from 64 to 256.

### Build timestamp

1684339504571

**Comment by SHIELDXIE** [comment]
I had a similar problem, it went to 64kbps quality and then never went back to 256

Operating System Version: Windows 11 22H2

Built on 2023.5.17 1:25:48 p.m. | Quasar v2.11.10

**Comment by TheNewSkai** [comment]
I also have this issue. Most songs in my library will play at 64kbps but some will still play at 256kbps. 

I'm also on Windows 10 22H2.

Downloaded Cider 2.0 at 9:40pm pst May 21 2023, if that's relevant.

**Comment by SHIELDXIE** [comment]
> I had a similar problem, it went to 64kbps quality and then never went back to 256我有一个类似的问题，它去64kbps 的质量，然后再也没有回到256
> 
> Operating System Version: Windows 11 22H2操作系统版本: Windows 1122H2
> 
> Built on 2023.5.17 1:25:48 p.m. | Quasar v2.11.10建于2023年5月17日下午1:25:48 | 类星体 v2.11.10

I found that pressing "Ctrl+R" to refresh the interface can temporarily restore 256kbps, if it goes back to 64 then refresh again

**Comment by coredev-uk** [comment]
We have had a lot of people bring this up. About a month ago we changed it to display the flavor of the music, which is more accurate. However, this is something that MusicKit controls and (to my knowledge) we cannot directly control. Certain songs may only play in 64, but the docs say that MusicKit should dynamically set the bitrate based on your bandwidth.

**Comment by coredev-uk** [comment]
We've since removed the bitrate indicator because of the out roar from the community. As I said previous, this is something we cannot control.

**Comment by alexvojacek** [comment]
Clearly something is not properly being setup or musickit is having a fatal bug because doing Ctrl+R as suggested here, fixed the issue.
Rather than closing in it and saying "not our fault"  you should investigate further.  I've purchased this program to help you in the development, saying "it's not our fault" and not doing anything about it is not nice.

Playing back at 64kbits completely ruins the experience for me, the program is unusable at that bitrate, I can hear the difference.

**Comment by alexvojacek** [comment]
> We've since removed the bitrate indicator because of the out roar from the community. As I said previous, this is something we cannot control.

Removing the bitrate indicator is an even WORSE decision than not doing something about it.  Now I will never know if a track is streaming at lower than acceptable level quality.   You should leave the option to enable/disable this so everyone can decide on their own.  Taking it out is really bad.

**Comment by coredev-uk** [comment]
I'm really sorry you feel that way,  but most-all users almost certainly cant tell the difference in audio quality either by the fact that they probably don't have advanced audio equipment to view what bitrate the music is playing at. 

We have looked into this thoroughly, coming up with a bitrate calculator that supposedly calculated based on the downlink provided by the renderer window. However this doesn't seem to be the cause as in some cases with an optimal downlink value it provides us with music with the 64 flavor. We also originally checked if it was based on choosing first m3u8 that the `webPlayback` call, but this also seems to differ from time to time. Our audio engineer stated that it is 64, but other member of the team including myself, disagree with this, thinking that the audio is 256, just occasionally drops to 64 at the start of a song, presumably due to a limited bandwidth. 

We are not paid to do this, donations and purchases go towards maintaining our API and other developer services required to keep the app running, so please don't come here with this attitude towards it all.

As for the bitrate indicator, this caused so many issues from no-doubt people that probably can't tell the difference between audio qualities (with the reason is said previously), so we disabled the option to prevent any more. Why don't you ask Apple why they don't have a bitrate indicator and they'll probably give you a similar response. You can still easily check the flavor if you really want (using `MusicKit.getInstance().nowPlayingItem.flavor` in devtools console).  We have had a user come up with a solution, however this is not optimal, and will make the app experience worse overall. 

We've been trying our best to learn about MusicKit, but there is little-to-no documentation on the whole bitrate area. MusicKitJS isn't anywhere near the standard as its Swift implementation it terms of docs and support. This is early access software so design decisions are made all the time, if a huge community out-pour comes for this feature, we can re implement it, but we don't simply add features because one user wanted it.

**Comment by cryptofyre** [comment]
Going on add on to this and say while we are working on a custom library to implement AM playback in Rust it likely won't see production use until next year.

Demo:

https://github.com/ciderapp/Cider-2/assets/33162551/709a14cd-7d14-40c5-89c9-c4d2b991066b

**Comment by alexvojacek** [comment]
Thank you for the update.  It seems Apple is not interested in updating their libraries and simply don't care if the audio quality is affected because of this.
For me this is a deal breaker.  I've subscribed to Apple Music because it was available on my country at a reduced price and had hi-res.  Then I've found out that most tracks available at Hi-Res weren't available at Hi-Res at Apple Music yet, then the App crashed constantly,  I though I found the solution with your App but the side effect of listening to music in 64kbit lossy AAC compared to 3744kbits 192khz-24bit Loseless on Amazon Music HD is just too much.
I've purchase a very expensive equipment to be able to enjoy music in the best quality possible.  I just cancelled my Apple Music subscription.  I hope you can make a better library than Apple and I'm so sorry that Apple cares so little about their own libraries.
